name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install sphinx breathe sphinx_copybutton sphinx_tabs sphinx_rtd_theme sphinx_favicon
          sudo apt install doxygen

      - name: Build main
        working-directory: ./src/docs
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          make html 

      - name: Build test
        working-directory: ./src/docs
        if: ${{ github.ref == 'refs/heads/test' }}
        run: |
          git fetch --tags
          git checkout main -- conf.py
          make html 

      - name: Deploy ROS:noetic version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build/html
          destination_dir: noetic
          force_orphan: true

      - name: Deploy ROS:iron version to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/test'}}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/docs/build/html
          destination_dir: iron
          force_orphan: true

